apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ai-platform-vs
spec:
  hosts:
    - ai-platform
  http:
    - timeout: 3s
      retries:
        attempts: 2
        perTryTimeout: 1s
        retryOn: 5xx,connect-failure,refused-stream
